name: Write README
on: [push]
jobs:
    Write-README:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - run: npm ci
            - run: npm run build
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                commit_message: 'Update README'
                commit_user_name: 'GitHub Actions'